name: Test and Build

on:
  push:
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: ./gradlew test
        
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Lint debug
        run: ./gradlew lintDebug
        
      - uses: actions/upload-artifact@master
        with:
          name: lint-results-debug.html
          path: app/build/reports/lint-results-debug.html
          
      - uses: actions/upload-artifact@master
        with:
          name: lint-results-debug.txt
          path: app/build/reports/lint-results-debug.txt
  
  build:
    needs: [ unit_tests, lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Debug APK
        run: ./gradlew --warning-mode all assembleDebug

      - uses: actions/upload-artifact@master
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      # - uses: actions/upload-artifact@master
      #   with:
      #     name: mapping.txt
      #     path: app/build/outputs/mapping/debug/mapping.txt
